FIND_PATH(LIBTCOD_INCLUDE_DIR libtcod.h
    HINTS 
    ${LIBTCOD}
    PATH_SUFFIXES
    include
)

find_library(LIBTCOD_LIBRARY NAMES libtcod libtcodgui
    HINTS 
    ${LIBTCOD}
)

set(LIBTCOD_LIBRARIES ${LIBTCOD_LIBRARY} )
set(LIBTCOD_INCLUDE_DIRS ${LIBTCOD_INCLUDE_DIR} )

INCLUDE(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set LIBXML2_FOUND to TRUE
# if all listed variables are TRUE
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBTCOD DEFAULT_MSG LIBTCOD_LIBRARY LIBTCOD_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBTCOD_INCLUDE_DIR LIBTCOD_LIBRARY)
